;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        TeX-insert-backslash
        TeX-newline
        beginning-of-visual-line
        copy-region-as-kill
        counsel-M-x
        doom/forward-to-last-non-comment-or-eol
        end-of-visual-line
        ibuffer-mark-for-delete
        kill-region
        mouse-drag-mode-line
        ns-do-hide-others
        ns-paste-secondary
        org-beginning-of-line
        org-cycle
        org-edit-special
        org-end-of-line
        org-force-self-insert
        org-return
        org-self-insert-command
        org-yank
        undo-fu-only-undo
        xah-copy-line-or-region
        xah-cut-line-or-region
        xah-cycle-hyphen-underscore-space
        xah-extend-selection
        xah-fly-command-mode-activate
        xah-fly-insert-mode-activate
        xah-forward-right-bracket
        xah-paste-or-paste-previous
        xah-select-line
        xah-shrink-whitespaces
        ))

(setq mc/cmds-to-run-once
      '(
        counsel-grep-or-swiper
        indent-for-tab-command
        isearch-repeat-forward
        mode-line-previous-buffer
        sim/enable-alt-modifier
        toggle-frame-fullscreen
        ))
