;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        doom/backward-to-bol-or-indent
        doom/forward-to-last-non-comment-or-eol
        org-open-line
        org-return
        org-self-insert-command
        wdired--self-insert
        xah-fly-command-mode-activate
        xah-fly-insert-mode-activate
        ))

(setq mc/cmds-to-run-once
      '(
        consult-yank-pop
        ))
