#+TITLE:A emacs doom configuration
#+DATE:    Juli 9, 2021

* Description
The ~sieman emacs doom~ configuration is without evil keybindings. The keybinding is a mix standard (doom) emacs and xah-fly-keys, some ideas inspired from Intellij Idea, Firefox and [[http://emacsrocks.com/][emacs-rocks]].

* Switch Profiles
I like to switch emacs profiles to try other configurations, therefore a shell script ~emacs-switcher.sh~ exists. It works well together with [[https://github.com/plexus/chemacs2][chemacs2]]. ~emacs-switcher.sh~ offers you to use one profile at time and ~chemacs2~ you can use multiply profiles at time.

With symbolic links it is easy to change a profile. And ~emacs-switcher.sh~ do change symbolic links. Therfore all emacs configuration is under the =~/.e= folder.

=~/.e/=:
- =others=
- =sieman.doom.d=
- =sieman.emacs.d=

=.emacs.d -> ~/.e/sieman.emacs.d=

=.doom.d -> ~/.e/sieman.doom.d=

* todo:
 - describe ~emacs-switcher.sh~
 - secret file
 - git clones ...
 - chemacs

#+begin_src emacs-lisp  :tangle ~/.emacs-profiles.el
(
 ("default" . ((user-emacs-directory . "~/.e/sieman.emacs.d")
               (env . (("DOOMDIR" . "~/.e/sieman.doom.d")))))

 ("hlissner" . ((user-emacs-directory . "~/.e/others/hlissner.emacs.d")
               (env . (("DOOMDIR" . "~/.e/others/hlissner.doom.d")))))

 ("doom" . ((user-emacs-directory . "~/.e/others/doom.emacs.d")
               (env . (("DOOMDIR" . "~/.e/others/doom.doom.d")))))
 ("spacemacs" . ((user-emacs-directory . "~/.e/others/spacemacs.emacs.d")
               (env . (("SPACEMACSDIR" . "~/.e/others/spacemacs.spacemacs.d")))))
 ("magnars" . ((user-emacs-directory . "~/.e/others/magnars.vanilla")))
 ("prelude" . ((user-emacs-directory . "~/.e/others/prelude.distro")))
 ("centaur" . ((user-emacs-directory . "~/.e/others/centaur.distro")))

 )
#+end_src

#+begin_src emacs-lisp :tangle ~/.emacs.secrets
(setq user-full-name "<first name> <last name>")
(setq calendar-location-name "Hamburg, Germany")
(setq calendar-latitude 53.57532)
(setq calendar-longitude 10.01534)
(setq calendar-location-name "")

(setq projectile-project-search-path '(
       "~/development/projects"
       ))
#+end_src

* Programming languages installation
Tools like [[https://brew.sh/][brew]] to install additional Software is required.
** Clojure
#+begin_src shell
brew install clojure leiningen
brew install clojure-lsp/brew/clojure-lsp-native
brew install borkdude/brew/clj-kondo
#+end_src
** Javascript
#+begin_src shell
npm install -g typescript-language-server
#+end_src
** JSON
jq - Command-line JSON processor
#+begin_src shell
brew install jq
#+end_src
** WEB
#+begin_src shell
npm install -g js-beautify
npm install -g stylelint
#+end_src
* Emacs Distro
** [[https://github.com/seagle0128/.emacs.d][Centaur Emacs]]
#+begin_src shell
git clone --depth 1 https://github.com/seagle0128/.emacs.d.git ~/.e/others/centaur.distro
#+end_src

** [[https://www.spacemacs.org][Spacemacs]]

#+begin_src shell
git clone --depth 1 https://github.com/syl20bnr/spacemacs ~/.e/others/spacemacs.emacs.d
mkdir ~/.e/others/spacemacs.spacemacs.d
#+end_src

** [[https://github.com/purcell/emacs.d][Purcell]]
* Font

[[https://typeof.net/Iosevka/][Iosevka]]

#+begin_src shell
 brew tap homebrew/cask-fonts
 brew install --cask font-iosevka
 brew install font-iosevka-ss04
 brew install font-iosevka-aile
#+end_src

[[https://github.com/tonsky/FiraCode][Fira Code]] just download the zip file and for Mac Os us the _ttf_ folder. [[https://github.com/tonsky/FiraCode/wiki/Emacs-instructions][Emacs instructions]]

Doom support ligatures see documantation.

Overpass [[https://github.com/gitfool/nerd-fonts/tree/master/patched-fonts/Overpass][Nerd Font]]
